# Files for P635L and R636Q mice
samples:
  P635L:
    "21s003516": "/g/steinmetz/incoming/solexa/2021-10-15-HWFVFBGXJ"
    "21s003517": "/g/steinmetz/incoming/solexa/2021-10-15-HWFVFBGXJ/"
    "21s003518": "/g/steinmetz/incoming/solexa/2021-10-15-HWFVFBGXJ"
    "21s003519": "/g/steinmetz/incoming/solexa/2021-10-15-HWFVFBGXJ"
    "21s003520": "/g/steinmetz/incoming/solexa/2021-10-15-HWFVFBGXJ"
    "21s003515": "/g/steinmetz/incoming/solexa/2021-10-15-HW7WLBGXJ"
    "21s003511": "/g/steinmetz/incoming/solexa/2021-10-15-HW7WLBGXJ"
    "21s003512": "/g/steinmetz/incoming/solexa/2021-10-15-HW7WLBGXJ"
    "21s003513": "/g/steinmetz/incoming/solexa/2021-10-15-HW7WLBGXJ"
    "21s003514": "/g/steinmetz/incoming/solexa/2021-10-15-HW7WLBGXJ"
    "21s003506": "/g/steinmetz/incoming/solexa/2021-10-04-H5JYHBGXK"
    "21s003507": "/g/steinmetz/incoming/solexa/2021-10-04-H5JYHBGXK"
    "21s003508": "/g/steinmetz/incoming/solexa/2021-10-04-H5JYHBGXK"
    "21s003509": "/g/steinmetz/incoming/solexa/2021-10-04-H5JYHBGXK"
    "21s003510": "/g/steinmetz/incoming/solexa/2021-10-04-H5JYHBGXK"
  R636Q:
    "22s000637": "/g/steinmetz/incoming/solexa/2022-03-04-HF3M5BGXL"
    "22s000638": "/g/steinmetz/incoming/solexa/2022-03-04-HF3M5BGXL"
    "22s000641": "/g/steinmetz/incoming/solexa/2022-03-04-HF3M5BGXL"
    "22s000639": "/g/steinmetz/incoming/solexa/2022-03-04-HF3M5BGXL"
    "22s000640": "/g/steinmetz/incoming/solexa/2022-03-04-HF3M5BGXL"
    "22s000629": "/g/steinmetz/incoming/solexa/2022-03-04-HKJG7BGXL"
    "22s000628": "/g/steinmetz/incoming/solexa/2022-03-04-HKJG7BGXL"
    "22s000627": "/g/steinmetz/incoming/solexa/2022-03-04-HKJG7BGXL"
    "22s000630": "/g/steinmetz/incoming/solexa/2022-03-04-HKJG7BGXL"
    "22s000631": "/g/steinmetz/incoming/solexa/2022-03-04-HKJG7BGXL"
    "22s000636": "/g/steinmetz/incoming/solexa/2022-03-04-HKJNFBGXL"
    "22s000634": "/g/steinmetz/incoming/solexa/2022-03-04-HKJNFBGXL"
    "22s000635": "/g/steinmetz/incoming/solexa/2022-03-04-HKJNFBGXL"
    "22s000632": "/g/steinmetz/incoming/solexa/2022-03-04-HKJNFBGXL"
    "22s000633": "/g/steinmetz/incoming/solexa/2022-03-04-HKJNFBGXL"
  P635L_after_base_editing:
    "22s002889": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002890": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002891": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002892": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002888": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002885": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002886": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002887": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002883": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002880": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002881": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002882": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002884": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002878": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s002879": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003390": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003387": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003388": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003389": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003385": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003383": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003384": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003386": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
    "22s003382": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-26-AAAN2YTHV"
  R636Q_after_base_editing:
    "22s002899": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002900": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002901": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002902": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002897": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002896": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002895": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002894": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002898": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s002893": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s003395": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s003394": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s003393": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s003392": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s003396": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    "22s003391": "/g/steinmetz/STOCKS/Data/Assay/sequencing/2022/2022-08-29-AAANJVNHV"
    
# Samples metadata link
samples_metadata: "/g/steinmetz/project/dcm_lgreads/mouse_bulkRNA/config/samples_metadata.txt"

# Mutations
mutation: ["R636Q", "P635L"]
  
  